#!/usr/bin/env python3
"""
build_tokens.py — rebuild tokens/*.css from _ds_manifest.json.

The Claude Design export ships styles.css (an @import list) and _ds_manifest.json (every
custom property with its value, file and scope) but not the tokens/ folder itself. This
writes that folder back so styles.css, the guideline cards and _ds_bundle.js render
outside Claude Design.

    python3 scripts/build_tokens.py            # from skills/ichita-design/

What comes from where:
  * Every custom property — verbatim from the manifest (name, value, file, scope, order).
  * @font-face — the manifest's font list, pointed at this repo's assets/fonts/ with
    local() first, so an installed face wins and nothing 404s.
  * The few non-token rules each file needs (the data-ground paint, the typeset weight
    hook, Thai leading, .ich-figure, .ich-nowrap, the four patterns) are RECONSTRUCTED
    from the rules written in design.md / readme.md / fonts.md. The Design project's
    originals were not exported. Do not upload these files back to Claude Design — its
    own tokens/ are the source of record there.
"""
import json, os, re, collections

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIRS = {"TH Aeonik": "th-aeonik", "Aeonik": "aeonik", "Betatron": "betatron",
             "Bai Jamjuree": "bai-jamjuree"}
FONT_ROOT = "../../../assets/fonts"   # tokens/ -> skills/ichita-design -> skills -> repo

HEADER = ("/* GENERATED by scripts/build_tokens.py from _ds_manifest.json — do not edit.\n"
          "   Custom properties are verbatim from the manifest; rules marked RECONSTRUCTED\n"
          "   are written from the spec in design.md / readme.md / fonts.md. */\n")

EXTRA = {
"tokens/base.css": """
/* RECONSTRUCTED — fonts.md §1 and §14, readme.md "Audited 10 Aug 2026". */
body{margin:0;font-family:var(--font-sans);font-weight:var(--weight-body);
  line-height:var(--leading-normal);color:var(--text-primary);background:var(--surface-page);
  font-synthesis:none}
strong,b{font-weight:var(--weight-strong)}
h1,h2,h3,h4,h5,h6{font-weight:var(--weight-heading);letter-spacing:var(--tracking-tight)}
:lang(th),.ich-th,.th{line-height:var(--leading-thai);letter-spacing:0}
.ich-figure{font-weight:var(--weight-bold);font-variant-numeric:tabular-nums;
  letter-spacing:var(--tracking-figure)}
.ich-nowrap{white-space:nowrap}
""",
"tokens/grounds.css": """
/* RECONSTRUCTED — design.md: a ground paints the field and rebinds the text together. */
[data-ground]{background:var(--ground-bg);color:var(--text-primary)}
""",
"tokens/patterns.css": """
/* RECONSTRUCTED — design.md §4: shapes Blue Grey 03, ground Blue Grey 01 or Ichita Blue only.
   An approximation of the four PDF patterns (p.19), not a trace of them. */
.ich-pattern{background-color:var(--pattern-bg-canvas);--_s:var(--pattern-shape)}
.ich-pattern--accent{background-color:var(--pattern-bg-accent)}
.ich-pattern--h-bars{background-image:linear-gradient(var(--_s) 0 14%,transparent 14% 22%,
  var(--_s) 22% 31%,transparent 31% 40%,var(--_s) 40% 45%,transparent 45% 55%,
  var(--_s) 55% 58%,transparent 58% 68%,var(--_s) 68% 69.5%,transparent 69.5% 80%,
  var(--_s) 80% 80.8%,transparent 80.8%)}
.ich-pattern--v-bars{background-image:linear-gradient(90deg,var(--_s) 0 9%,transparent 9% 13%,
  var(--_s) 13% 18%,transparent 18% 30%,var(--_s) 30% 42%,transparent 42% 46%,
  var(--_s) 46% 49%,transparent 49% 63%,var(--_s) 63% 70%,transparent 70% 82%,
  var(--_s) 82% 84%,transparent 84%)}
.ich-pattern--blocks{background-image:linear-gradient(90deg,var(--_s) 0 34%,transparent 34% 40%,
  color-mix(in srgb,var(--_s) 55%,transparent) 40% 66%,transparent 66% 72%,
  color-mix(in srgb,var(--_s) 22%,transparent) 72% 92%,transparent 92%)}
.ich-pattern--dots{background-image:radial-gradient(var(--_s) 34%,transparent 36%);
  background-size:18px 18px;-webkit-mask-image:linear-gradient(#000,transparent);
  mask-image:linear-gradient(#000,transparent)}
""",
}


def font_faces(fonts):
    out = []
    for f in fonts:
        fam, w, st = f["family"], f["weight"], f["style"]
        srcs = []
        for p in f["files"]:
            base = os.path.basename(p)
            suffix = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", os.path.splitext(base)[0].split("-")[-1])
            srcs.append('local("%s %s")' % (fam, suffix))
            srcs.append('url("%s/%s/%s")' % (FONT_ROOT, FONT_DIRS.get(fam, ""), base))
        out.append('@font-face{font-family:"%s";font-weight:%s;font-style:%s;font-display:swap;'
                   "src:%s}" % (fam, w, st, ",".join(srcs)))
    return "\n".join(out) + "\n"


def main():
    m = json.load(open(os.path.join(HERE, "_ds_manifest.json"), encoding="utf-8"))
    files = collections.OrderedDict((p, collections.OrderedDict()) for p in m["globalCssPaths"]
                                    if p.startswith("tokens/"))
    for t in m["tokens"]:
        scopes = files.setdefault(t["definedIn"], collections.OrderedDict())
        scopes.setdefault(t.get("scope", ":root"), []).append(t)
    os.makedirs(os.path.join(HERE, "tokens"), exist_ok=True)
    for path, scopes in files.items():
        css = [HEADER]
        if path == "tokens/fonts.css":
            css.append(font_faces(m["fonts"]))
        for sel, toks in scopes.items():
            css.append(sel + "{\n" + "".join("  %s:%s;\n" % (t["name"], t["value"]) for t in toks) + "}\n")
        css.append(EXTRA.get(path, ""))
        with open(os.path.join(HERE, path), "w", encoding="utf-8") as fh:
            fh.write("".join(css))
        print("wrote", path, sum(len(v) for v in scopes.values()), "tokens")


if __name__ == "__main__":
    main()
