#!/usr/bin/env python3
"""Build WOFF2/WOFF for TH-Aeonik, with CSS, and verify the browser line box.

BUILT AND HELD, NOT SERVED. Phase 5 of the 2026-08-05 plan says to produce this and
NOT deploy it, and the reason is a licence position nobody has resolved: TH-Aeonik
is Aeonik's Latin outlines merged with Bai Jamjuree's Thai, so serving it as a
webfont redistributes CoType's outlines to every visitor. That is a different
permission from using them in a PDF. Until CoType answers in writing, the output of
this script belongs in the repo and on nobody's CDN.

What it is for meanwhile: the third renderer. Word is measured by
scripts/win_office_pitch.py, LibreOffice by scripts/qc_check_th_font_doc.py, and a
browser is the one that most resembles CoreText — so a browser agreeing on 1537 is
the closest thing to macOS evidence available without a Mac.

THE CHECK IS THE POINT, not the files. `--verify` loads the built font in headless
Chrome and measures the height of a stack of lines, which is the same question the
Office probe asks, put to a completely independent layout engine. Browsers read
`sTypo` when USE_TYPO_METRICS is set and `hhea` otherwise, and this font sets both
to 1537 — so a browser that reports anything else falsifies the "unify all three
metric sets" strategy rather than revealing a browser quirk.

`unicode-range` is emitted per subset so a Latin-only page never downloads the Thai.
It is a performance property, not a correctness one — the font is one file and the
ranges only tell the browser when it is needed.

    python3 scripts/build_th_web.py
    python3 scripts/build_th_web.py --verify
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))
ROOT = SCRIPTS.parent

SRC_DIR = ROOT / "assets" / "fonts" / "th-aeonik"
OUT_DIR = ROOT / "assets" / "fonts" / "th-aeonik-web"

# The weights a web page actually uses. Not all 14 — a webfont payload is a cost
# per visitor, and Air/Thin/Black exist for display work that does not happen in a
# browser. Add one here if a real page needs it.
WEB_WEIGHTS = {
    "Light": (300, "normal"),
    "LightItalic": (300, "italic"),
    "Regular": (400, "normal"),
    "RegularItalic": (400, "italic"),
    "Medium": (500, "normal"),
    "MediumItalic": (500, "italic"),
    "Bold": (700, "normal"),
    "BoldItalic": (700, "italic"),
}

# Latin-1 + Latin Extended-A + the punctuation and symbols ICHITA documents use,
# then Thai. Split so a Latin-only page skips the Thai range.
UNICODE_RANGES = {
    "latin": ("U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, "
              "U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, "
              "U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"),
    "greek-math": ("U+0370-03FF, U+2070-209F, U+2190-21FF, U+2200-22FF, "
                   "U+2300, U+00B1, U+00B5, U+00D8"),
    "thai": "U+0E00-0E7F, U+200B, U+25CC",
}

# What the font declares, and therefore what a browser must compute. hhea and sTypo
# both carry this, so neither of the two rules a browser might use can disagree.
EXPECTED_EM = 1537
LINE_TOL_PX = 0.75          # sub-pixel; browsers round layout to 1/64 px


def build(src_dir, out_dir):
    """Write .woff2 and .woff beside each other. Returns the list of faces done."""
    from fontTools.ttLib import TTFont

    out_dir.mkdir(parents=True, exist_ok=True)
    done = []
    for face in WEB_WEIGHTS:
        src = src_dir / f"TH-Aeonik-{face}.otf"
        if not src.exists():
            print(f"  {face:16s} SKIP — {src.name} not built")
            continue
        sizes = {}
        for flavor in ("woff2", "woff"):
            font = TTFont(str(src))
            font.flavor = flavor
            dst = out_dir / f"TH-Aeonik-{face}.{flavor}"
            font.save(str(dst))
            font.close()
            sizes[flavor] = dst.stat().st_size
        print(f"  {face:16s} woff2 {sizes['woff2'] / 1024:6.1f} KB  "
              f"woff {sizes['woff'] / 1024:6.1f} KB")
        done.append(face)
    return done


def write_css(faces, out_dir):
    """@font-face blocks, one per subset per face, woff2 first."""
    lines = [
        "/* TH Aeonik — ICHITA. GENERATED by scripts/build_th_web.py; do not edit.",
        " *",
        " * NOT CLEARED FOR SERVING. This font merges Aeonik's Latin outlines with",
        " * Bai Jamjuree's Thai, so publishing it redistributes CoType's outlines to",
        " * every visitor — a different permission from embedding them in a PDF.",
        " * Do not deploy until CoType has answered in writing.",
        " *",
        f" * Line box {EXPECTED_EM}/1000 em, carried by hhea AND sTypo, so a browser",
        " * computes the same line height whichever of the two it reads. Set",
        " * line-height explicitly anyway if a design needs a specific rhythm —",
        " * inheriting 'normal' means inheriting 1.537, which is correct for Thai",
        " * and looser than a Latin-only design usually wants.",
        " */",
        "",
    ]
    for face in faces:
        weight, style = WEB_WEIGHTS[face]
        for subset, rng in UNICODE_RANGES.items():
            lines += [
                "@font-face {",
                "  font-family: 'TH Aeonik';",
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f"  src: url('TH-Aeonik-{face}.woff2') format('woff2'),",
                f"       url('TH-Aeonik-{face}.woff') format('woff');",
                f"  unicode-range: {rng};",
                f"  /* {subset} */",
                "}",
                "",
            ]
    path = out_dir / "th-aeonik.css"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _win_url(path):
    """A file: URL a Windows browser can open, from a WSL path.

    Only correct for paths that live on a DRIVE. A path under /home maps to the UNC
    \\\\wsl.localhost\\Ubuntu\\... form, and a UNC file URL is not
    "file:///" + the path with slashes flipped — that produces file://///wsl...,
    which Edge accepts and then fails to read, so the page silently laid out in
    Arial and the probe reported the browser disagreeing with the font by 387 units.
    Staging onto C: (see _stage_for_windows) avoids the whole question.
    """
    out = subprocess.run(["wslpath", "-w", str(path)],
                         capture_output=True, text=True)
    win = out.stdout.strip() if out.returncode == 0 else str(path)
    if win.startswith("\\\\"):
        return "file:" + win.replace("\\", "/").replace(" ", "%20")
    return "file:///" + win.replace("\\", "/").replace(" ", "%20")


def _serve(directory):
    """Serve `directory` on a free localhost port in a daemon thread.

    Returns (server, port), or (None, None). The caller must call
    server.shutdown(). An HTTP origin is what makes @font-face work at all — see
    the note in verify().
    """
    import functools
    import http.server
    import threading
    try:
        handler = functools.partial(http.server.SimpleHTTPRequestHandler,
                                    directory=str(directory))
        # Quiet: the request log would otherwise interleave with the report.
        hits = []
        def _log(self, fmt, *a):
            hits.append(fmt % a if a else fmt)
        handler.log_message = _log
        server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    except OSError:
        return None, None
    threading.Thread(target=server.serve_forever, daemon=True).start()
    server.hits = hits
    return server, server.server_address[1]


def verify(out_dir, face="Regular", size_px=100):
    """Measure the computed line box in headless Chrome. Returns (ok, detail).

    Measured as the height difference between a 1-line and a 6-line block, which
    cancels any padding the browser or the test page contributes — the same
    differencing trick the PowerPoint probe uses, and for the same reason.
    """
    # Linux browser first, then the WINDOWS one via WSL. There is usually no
    # Chromium installed in WSL, and Edge on Windows is the same Blink engine —
    # so falling back to it is the difference between measuring a browser and
    # reporting a gap. Paths have to be handed over as Windows paths, hence
    # wslpath below.
    chrome = (shutil.which("google-chrome") or shutil.which("chromium")
              or shutil.which("chromium-browser")
              or shutil.which("google-chrome-stable"))
    win_browser = None
    if chrome is None:
        for candidate in (
                "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe",
                "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe",
                "/mnt/c/Program Files/Microsoft/Edge/Application/msedge.exe",
                "/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"):
            if Path(candidate).exists():
                win_browser = candidate
                break
    if chrome is None and win_browser is None:
        return None, ("no Blink browser reachable from here, on Linux or on "
                      "Windows — the browser check could not run, and that is a "
                      "GAP rather than a pass")

    font = out_dir / f"TH-Aeonik-{face}.woff2"
    if not font.exists():
        return None, f"{font.name} not built"

    # Under WSL the page has to live somewhere the Windows browser can read, and
    # the font URL has to be a Windows path. A /tmp path would resolve to the
    # browser's own C:\tmp and silently load nothing — the font would fall back and
    # the measurement would be of a substitute.
    # SERVED OVER HTTP, not opened from disk. A `file://` @font-face src is treated
    # as cross-origin by Blink and is refused even with
    # --allow-file-access-from-files, so the page laid out in Arial and the probe
    # read that as the browser disagreeing with the font by 387 units. An HTTP
    # origin removes the question entirely, and WSL2 forwards localhost to Windows
    # so the same server works for both browsers.
    tmp = Path(tempfile.mkdtemp(prefix="th-web-"))
    shutil.copy2(font, tmp / font.name)
    server, port = _serve(tmp)
    if server is None:
        return None, "could not start a local HTTP server — GAP, not a pass"
    font_url = f"http://localhost:{port}/{font.name}"
    html = tmp / "probe.html"
    html.write_text(f"""<!doctype html><meta charset="utf-8">
<style>
  @font-face {{ font-family: 'TH Aeonik'; src: url('{font_url}') format('woff2'); }}
  body {{ margin: 0; }}
  .p {{ font-family: 'TH Aeonik'; font-size: {size_px}px; line-height: normal;
        margin: 0; white-space: pre; }}
</style>
<div class="p" id="one">Hg</div>
<div class="p" id="six">Hg
Hg
Hg
Hg
Hg
Hg</div>
<script>
  // @font-face loads LAZILY and ASYNCHRONOUSLY. The first version measured
  // immediately and always caught the fallback, then blamed the URL. Load it
  // explicitly and wait for it before measuring anything.
  async function run() {{
  try {{ await document.fonts.load('{size_px}px TH-Aeonik-probe'); }} catch (e) {{ }}
  try {{ await document.fonts.load('{size_px}px \"TH Aeonik\"'); }} catch (e) {{ }}
  await document.fonts.ready;
  const one = document.getElementById('one').getBoundingClientRect().height;
  const six = document.getElementById('six').getBoundingClientRect().height;
  // Whether the FONT ACTUALLY LOADED is part of the measurement, and
  // document.fonts.check() is NOT good enough for it: it returns true when the
  // text is renderable with the fonts available, INCLUDING a fallback, so it said
  // "loaded" while the page was laid out in Arial. Compared by ADVANCE WIDTH
  // against a deliberately non-existent family instead — two different faces
  // cannot measure the same string to the same fraction of a pixel.
  const c = document.createElement('canvas').getContext('2d');
  c.font = '{size_px}px "TH Aeonik", monospace';
  const wOurs = c.measureText('Hamburgefonstiv').width;
  c.font = '{size_px}px "NoSuchFamily-ZZ", monospace';
  const wFallback = c.measureText('Hamburgefonstiv').width;
  const loaded = Math.abs(wOurs - wFallback) > 0.5;
  document.title = JSON.stringify({{one: one, six: six, loaded: loaded,
                                   wOurs: wOurs, wFallback: wFallback,
                                   pitch: (six - one) / 5}});
  }}
  run();
</script>
""", encoding="utf-8")

    exe = chrome or win_browser
    page_url = f"http://localhost:{port}/probe.html"
    try:
        out = subprocess.run(
            [exe, "--headless", "--disable-gpu", "--no-sandbox",
             "--virtual-time-budget=8000", "--dump-dom", page_url],
            capture_output=True, text=True, timeout=300)
    finally:
        server.shutdown()
    if out.returncode != 0:
        return None, (f"{Path(exe).name} exited {out.returncode}: "
                      f"{out.stderr[:300]}")

    import re
    m = re.search(r"<title>(\{.*?\})</title>", out.stdout)
    if not m:
        return None, "could not read the measurement back out of the DOM"
    data = json.loads(m.group(1).replace("&quot;", '"'))
    want_px = EXPECTED_EM / 1000 * size_px
    got = data["pitch"]
    if not data.get("loaded"):
        asked = [h for h in getattr(server, "hits", []) if ".woff2" in h]
        why = ("the browser never even REQUESTED the font file"
               if not asked else
               f"the browser requested it ({asked[0].strip()}) and still did not "
               f"use it")
        return None, (f"{why}. The browser did NOT load the webfont and laid the page "
                      f"out in a substitute — 'Hamburgefonstiv' measured "
                      f"{data.get('wOurs')} px against a known-bogus family's "
                      f"{data.get('wFallback')} px. Any pitch from this run is a "
                      f"measurement of the FALLBACK; fix the URL, not the font.")
    ok = abs(got - want_px) <= LINE_TOL_PX
    return ok, (f"line pitch {got:.2f} px at {size_px} px/em = "
                f"{got / size_px * 1000:.0f}/em, expected {want_px:.2f} px "
                f"({EXPECTED_EM}/em), tol {LINE_TOL_PX} px")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out-dir", default=str(OUT_DIR))
    ap.add_argument("--verify", action="store_true",
                    help="measure the computed line box in headless Chrome")
    args = ap.parse_args()
    out_dir = Path(args.out_dir)

    print(f"\nBuilding TH Aeonik webfonts -> {out_dir}")
    faces = build(SRC_DIR, out_dir)
    if not faces:
        print("\nnothing built — run scripts/build_th_aeonik.py first")
        return 1
    css = write_css(faces, out_dir)
    print(f"\n  {css.relative_to(ROOT)}  "
          f"({len(faces)} faces x {len(UNICODE_RANGES)} subsets)")

    rc = 0
    if args.verify:
        ok, detail = verify(out_dir)
        print(f"\nheadless Chrome: {detail}")
        if ok is None:
            print("  GAP — not run. This is not a pass.")
            rc = 1
        elif ok:
            print("  OK — the browser computes the box the font declares, which is "
                  "the independent confirmation that unifying hhea/sTypo/usWin "
                  "works outside Office.")
        else:
            print("  FAIL — a browser reads hhea, or sTypo when USE_TYPO_METRICS "
                  "is set, and this font sets BOTH to "
                  f"{EXPECTED_EM}. A disagreement falsifies the unified-metrics "
                  "strategy; do not write it off as a browser quirk.")
            rc = 1

    print("\nHELD, NOT SERVED — see the module docstring and the plan's Risks. "
          "The licence position on serving these is unresolved.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
